#!/usr/bin/env python

from front.FrontEnd import FrontEnd
from player.Player import Player
from curses import wrapper
from library.Library import Library

def main():
    player = Player()
    library = Library()
    front_end = FrontEnd(player,library)
    

if __name__ == "__main__":
    main()
